spring:
  application:
    name: ifdp-service
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/zoo
    username: zoo
    password: zoo
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    topics:
      zooclinic: zooclinic_topic
springdoc:
  swagger-ui:
    path: '/swagger-ui.html'
server:
  port: 8080
